#!/usr/bin/env python

import threading
from pie_break import pie_break
from sys import argv, exit

timer = None

# If a time and several urls are passed
if len(argv) >= 3:
    try:
        timer = pie_break.PieBreak(work_time=int(argv[1]), urls=argv[2:])
    except ValueError:
        work_time = input(
            'Try again. For how many minutes do you want to work? ')
        try:
            work_time = int(work_time)
        except ValueError:
            exit(
                'You use numbers like elon musk names children.. Exiting.')
        else:
            urls = []
            while True:
                if urls:
                    new_url = input('Another?: ')
                else:
                    new_url = input(
                        'If you want, enter a url by which to be \
                            interrupted: ')
                if not new_url:
                    break
                urls.append(new_url)

            timer = pie_break.PieBreak(work_time=work_time, urls=urls)
    timer.get_params()

# If only a working time is passed
elif len(argv) == 2:
    try:
        timer = pie_break.PieBreak(work_time=int(argv[1]))
    except ValueError:
        work_time = input(
            'Try again. For how many minutes do you want to work?')

# If no parameters are passed
else:
    timer = pie_break.PieBreak()

timer.start()
# print(timer.get_params())

while True:
    new_in = input("Add info while loop runs: ")
    print(new_in)
